### ISSUE TITLE
 status?

### ISSUE THREAD

**Issue by Lenheart357** [samisalreadytaken/sqdbg#1]
Is this project currently in completion status? How can I use it in VSCode

**Comment by Lenheart357** [comment]
I used it in VSCode, and all its other functions are effective except for adding breakpoints, which cannot take effect

**Comment by samisalreadytaken** [comment]
Did you read the notes in the README about breakpoints? Also if your script source names contain any path separators, you'll need to compile with `SQDBG_SOURCENAME_HAS_PATH`.

For reference, here are all available preprocessor definitions:
```
SQDBG_DISABLE_PROFILER
SQDBG_DISABLE_COMPILER
SQDBG_SOURCENAME_HAS_PATH
SQDBG_SUPPORTS_SET_INSTRUCTION
SQDBG_CALL_DEFAULT_ERROR_HANDLER
SQDBG_DONT_CONVERT_UTF8_BYTES_IN_UTF16
SQDBG_PRINTBUF_SIZE
SQDBG_COMPILER_MAX_PARAMETER_COUNT
SQDBG_COMPILER_MAX_UNARY_STACK
SQDBG_NET_BUF_SIZE
SQDBG_DEBUGGER_ECHO_OUTPUT
SQDBG_EXCLUDE_DEFAULT_MEMFUNCTIONS
```

**Comment by Lenheart357** [comment]
Thank you, I successfully used it. Your project is excellent.
